"""Tests use synthetic genotypes only. Never add real genetic data to tests/."""

import zipfile

from pipeline import compare, genotypes, qc

HEADER_23 = """# This data file generated by 23andMe at: Tue Jun 23 13:19:07 2020
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid\tchromosome\tposition\tgenotype
"""
ROWS_23 = [
    ("rs3131972", "1", "752721", "AG"),
    ("rs12124819", "1", "776546", "AA"),
    ("rs1000001", "2", "1000", "CT"),
    ("rs1000002", "2", "2000", "--"),
    ("rs1000003", "X", "3000", "A"),
    ("i7000001", "MT", "100", "G"),
]


def _write_23(tmp_path, rows=ROWS_23, name="genome_Test_v5_Full_2020.txt"):
    p = tmp_path / name
    p.write_text(HEADER_23 + "".join("\t".join(r) + "\n" for r in rows))
    return p


def test_parse_23andme_and_build_anchors(tmp_path):
    ds = genotypes.parse(_write_23(tmp_path))
    assert ds.vendor == "23andMe"
    assert ds.chip == "23andMe v5"
    assert ds.build == "GRCh37"
    assert any("matches GRCh37" in e for e in ds.build_evidence)
    assert [c.genotype for c in ds.calls] == ["AG", "AA", "CT", "--", "A", "G"]


def test_build_conflict_is_flagged_not_silently_resolved(tmp_path):
    rows = [("rs3131972", "1", "817341", "AG"), ("rs12124819", "1", "841166", "AA")]
    ds = genotypes.parse(_write_23(tmp_path, rows))
    assert ds.build == "CONFLICT"
    assert ds.warnings


def test_drive_escaped_flattened_text(tmp_path):
    # Google Drive's viewer escapes '#' and collapses newlines to spaces.
    flat = (HEADER_23.replace("#", "\\#").replace("\n", " ")
            + " ".join(" ".join(r) for r in ROWS_23) + " rs99 1")
    p = tmp_path / "flattened.txt"
    p.write_text(flat)
    ds = genotypes.parse(p)
    assert len(ds.calls) == len(ROWS_23)
    assert any("trailing" in w for w in ds.warnings)


def test_ancestrydna_zip_with_coded_chromosomes(tmp_path):
    txt = ("#AncestryDNA raw data download\n#reference human assembly build 37\n"
           "rsid\tchromosome\tposition\tallele1\tallele2\n"
           "rs3131972\t1\t752721\tA\tG\nrs5\t23\t500\tC\tC\nrs6\t26\t10\t0\t0\n")
    p = tmp_path / "dna.zip"
    with zipfile.ZipFile(p, "w") as z:
        z.writestr("AncestryDNA.txt", txt)
    ds = genotypes.parse(p)
    assert ds.vendor == "AncestryDNA"
    assert [(c.chrom, c.genotype) for c in ds.calls] == [("1", "AG"), ("X", "CC"), ("MT", "--")]


def test_qc_flags_truncation_and_heterozygosity(tmp_path):
    q = qc.qc(genotypes.parse(_write_23(tmp_path)))
    assert q["truncated"]
    assert q["autosomal_heterozygosity"] == round(2 / 3, 5)


def test_concordance_strand_and_palindromes(tmp_path):
    a = genotypes.parse(_write_23(tmp_path, [("rs1", "1", "1", "AG"), ("rs2", "1", "2", "AT"), ("rs3", "1", "3", "CC")], "a.txt"))
    b = genotypes.parse(_write_23(tmp_path, [("rs1", "1", "1", "TC"), ("rs2", "1", "2", "TA"), ("rs3", "1", "3", "CT")], "b.txt"))
    r = compare.concordance(a, b)
    assert r["counts"]["strand_flip"] == 1
    assert r["counts"]["palindromic_match_unverifiable_strand"] == 1
    assert r["counts"]["discordant"] == 1


# ---------------- analysis layer (synthetic) ----------------
from pipeline import analyze  # noqa: E402
from pipeline.genotypes import Call  # noqa: E402


def test_annotate_refuses_allele_mismatch():
    G = {"rs1": Call("rs1", "1", 10, "GT", 1)}
    row = analyze.annotate(G, [dict(rsid="rs1", gene="X", effect="A", other="G", tier="B", interp={0: "", 1: "", 2: ""})], "trait")[0]
    assert row["effect_count"] is None and "mismatch" in row["status"]


def test_apoe_calls():
    mk = lambda a, b: {"rs429358": Call("rs429358", "19", 1, a, 1), "rs7412": Call("rs7412", "19", 2, b, 2)}
    assert analyze.apoe(mk("TT", "CC"))["genotype"] == "ε3/ε3"
    assert analyze.apoe(mk("CT", "CC"))["genotype"] == "ε3/ε4"
    assert analyze.apoe(mk("TT", "CT"))["genotype"] == "ε2/ε3"


def test_plink_roh_finds_long_homozygous_block():
    snps = [(i * 10_000, (i % 7 == 0)) for i in range(1000)]            # heterozygous background
    snps += [(10_000_000 + i * 10_000, False) for i in range(400)]     # 4 Mb homozygous block
    snps += [(14_000_000 + i * 10_000, (i % 7 == 0)) for i in range(500)]
    runs = analyze._plink_roh("1", snps)
    assert len(runs) == 1 and 3.5 < runs[0]["length_mb"] < 4.6
