"""Curated variant knowledge base (public literature; no personal data).

Alleles are on the GRCh37 plus strand, as 23andMe/AncestryDNA report them. The
annotator refuses to interpret a site whose observed alleles are not {effect, other},
so a strand or allele error in this table surfaces as a flagged site, not a wrong claim.

`tier` is the strength of the genotype->phenotype link itself (A-D), independent of
whether the person was genotyped. `interp` maps effect-allele count (0/1/2) to text.
"""

TRAITS = [
    dict(rsid="rs12913832", gene="HERC2/OCA2", category="Appearance", trait="Eye colour (blue vs brown)",
         effect="G", other="A", tier="B",
         interp={0: "AA — strongly associated with brown eyes.", 1: "AG — usually brown or intermediate eyes; blue is uncommon.", 2: "GG — strongly associated with blue/light eyes."},
         note="The single strongest eye-colour locus in West Eurasians, but other genes (OCA2 rs1800407, TYR, SLC24A4…) modify it.",
         refs=["Sturm et al. 2008 AJHG", "Eiberg et al. 2008 Hum Genet"]),
    dict(rsid="rs1800407", gene="OCA2", category="Appearance", trait="Green/hazel eye modifier (R419Q)",
         effect="T", other="C", tier="C",
         interp={0: "CC — typical.", 1: "CT — one copy; associated with green/hazel shading on a blue background.", 2: "TT — two copies."},
         refs=["Duffy et al. 2007 AJHG"]),
    dict(rsid="rs1426654", gene="SLC24A5", category="Appearance", trait="Skin pigmentation (A111T)",
         effect="A", other="G", tier="B",
         interp={0: "GG — ancestral allele (common in Africa and East Asia).", 1: "AG — one copy of the derived lighter-pigmentation allele.", 2: "AA — two copies of the derived allele, near-universal in Europe and very common in West, Central and South Asia."},
         note="Explains a meaningful but partial share of the skin-tone difference between populations; dozens of other loci contribute.",
         refs=["Lamason et al. 2005 Science", "Mathieson et al. 2015 Nature"]),
    dict(rsid="rs16891982", gene="SLC45A2", category="Appearance", trait="Skin/hair pigmentation (L374F)",
         effect="G", other="C", tier="B",
         interp={0: "CC — ancestral.", 1: "CG — one derived (lighter) allele.", 2: "GG — two derived alleles; very common in Europe, less so in Central/South Asia."},
         refs=["Graf et al. 2005 Hum Mutat", "Soejima & Koda 2007"]),
    dict(rsid="rs1042602", gene="TYR", category="Appearance", trait="Freckling / lighter pigmentation (S192Y)",
         effect="A", other="C", tier="C",
         interp={0: "CC — typical.", 1: "AC — one copy.", 2: "AA — two copies."},
         refs=["Sulem et al. 2007 Nat Genet"]),
    dict(rsid="rs12203592", gene="IRF4", category="Appearance", trait="Sun sensitivity, freckles, hair lightness",
         effect="T", other="C", tier="B",
         interp={0: "CC — typical outside Europe.", 1: "CT — one copy; associated with more freckling and sun sensitivity.", 2: "TT — two copies."},
         refs=["Han et al. 2008 PLoS Genet", "Praetorius et al. 2013 Cell"]),
    dict(rsid="rs1805007", gene="MC1R", category="Appearance", trait="Red hair / fair skin (R151C)",
         effect="T", other="C", tier="B",
         interp={0: "CC — no copy of this red-hair variant.", 1: "CT — carrier; usually no red hair alone.", 2: "TT — two copies; strongly associated with red hair."},
         refs=["Valverde et al. 1995 Nat Genet"]),
    dict(rsid="rs1805008", gene="MC1R", category="Appearance", trait="Red hair / fair skin (R160W)",
         effect="T", other="C", tier="B",
         interp={0: "CC — no copy.", 1: "CT — carrier.", 2: "TT — two copies."},
         refs=["Valverde et al. 1995 Nat Genet"]),
    dict(rsid="rs3827760", gene="EDAR", category="Appearance", trait="Hair shaft thickness (V370A)",
         effect="G", other="A", tier="B",
         interp={0: "AA — ancestral; typical of West Eurasia and Africa.", 1: "AG — one copy of the East-Asian-associated 370A allele.", 2: "GG — two copies; associated with thicker, straighter hair."},
         note="An ancestry-informative marker: the derived allele is common in East Asia and the Americas and rare in Europe.",
         refs=["Fujimoto et al. 2008 Hum Mol Genet", "Kamberov et al. 2013 Cell"]),
    dict(rsid="rs17822931", gene="ABCC11", category="Appearance", trait="Earwax type / underarm odour",
         effect="T", other="C", tier="B",
         interp={0: "CC — wet earwax (typical).", 1: "CT — wet earwax (the dry type is recessive).", 2: "TT — dry earwax and reduced underarm odour."},
         note="Near-Mendelian recessive trait; the dry allele is very common in East Asia.",
         refs=["Yoshiura et al. 2006 Nat Genet"]),
    dict(rsid="rs4988235", gene="MCM6 (LCT enhancer)", category="Sensory & diet", trait="Lactase persistence (-13910 C>T)",
         effect="A", other="G", tier="B",
         interp={0: "GG — no European-type persistence allele; lactase activity typically declines after childhood.", 1: "AG — one persistence allele; dominant, so usually lactase-persistent.", 2: "AA — two persistence allele copies; lactase-persistent."},
         note="This is the European/Central-Asian-steppe persistence variant. Other persistence alleles exist (e.g. in East Africa and Arabia), so GG does not prove lactose intolerance.",
         refs=["Enattah et al. 2002 Nat Genet", "Itan et al. 2009 PLoS Comput Biol"]),
    dict(rsid="rs671", gene="ALDH2", category="Sensory & diet", trait="Alcohol flush (E504K)",
         effect="A", other="G", tier="B",
         interp={0: "GG — normal ALDH2 activity.", 1: "AG — reduced activity; alcohol flushing likely.", 2: "AA — near-absent activity; strong flushing."},
         note="Common in East Asia, rare elsewhere. Carriers who drink have raised oesophageal-cancer risk.",
         refs=["Brooks et al. 2009 PLoS Med"]),
    dict(rsid="rs1229984", gene="ADH1B", category="Sensory & diet", trait="Fast alcohol→acetaldehyde conversion (R48H)",
         effect="T", other="C", tier="B",
         interp={0: "CC — typical.", 1: "CT — one fast allele; associated with lower alcohol consumption.", 2: "TT — two fast alleles."},
         note="Common in East Asia and parts of West/Central Asia.",
         refs=["Bierut et al. 2012 Mol Psychiatry"]),
    dict(rsid="rs762551", gene="CYP1A2", category="Sensory & diet", trait="Caffeine metabolism inducibility (*1F)",
         effect="A", other="C", tier="C",
         interp={0: "CC — 'slower' inducibility genotype.", 1: "AC — intermediate.", 2: "AA — highly inducible ('fast') genotype."},
         note="Effect depends on smoking and other factors; replicated only modestly.",
         refs=["Sachse et al. 1999 Br J Clin Pharmacol", "Cornelis et al. 2006 JAMA"]),
    dict(rsid="rs72921001", gene="OR6A2 region", category="Sensory & diet", trait="Cilantro tastes 'soapy'",
         effect="A", other="C", tier="C",
         interp={0: "CC — typical.", 1: "AC — one copy; slightly more likely to report soapy taste.", 2: "AA — two copies."},
         note="GWAS association; explains a small fraction of variation in the trait.",
         refs=["Eriksson et al. 2012 arXiv:1209.2096 (23andMe)"]),
    dict(rsid="rs1815739", gene="ACTN3", category="Physiology", trait="Fast-twitch muscle α-actinin-3 (R577X)",
         effect="T", other="C", tier="B",
         interp={0: "CC (RR) — functional α-actinin-3 in fast-twitch fibres; over-represented in elite sprinters.", 1: "CT (RX) — functional protein present.", 2: "TT (XX) — no α-actinin-3; common (~18% of Europeans) and harmless; slightly over-represented in endurance athletes."},
         note="Protein effect is Tier B; the effect on athletic performance for an individual is small (Tier C).",
         refs=["Yang et al. 2003 AJHG", "MacArthur & North 2004"]),
    dict(rsid="rs4680", gene="COMT", category="Physiology", trait="COMT enzyme activity (Val158Met)",
         effect="A", other="G", tier="C",
         interp={0: "GG (Val/Val) — higher enzyme activity.", 1: "AG (Val/Met) — intermediate.", 2: "AA (Met/Met) — lower activity."},
         note="Enzyme effect is real; popular claims about personality or 'warrior/worrier' are weakly supported.",
         refs=["Lachman et al. 1996 Pharmacogenetics"]),
    dict(rsid="rs1801133", gene="MTHFR", category="Physiology", trait="Folate metabolism (C677T)",
         effect="A", other="G", tier="B",
         interp={0: "GG — typical enzyme activity.", 1: "AG — ~65% activity; no clinical significance on its own.", 2: "AA — ~30% activity; can raise homocysteine when folate is low."},
         note="Professional bodies (ACMG 2013) recommend AGAINST MTHFR testing for thrombophilia or pregnancy loss.",
         refs=["Frosst et al. 1995 Nat Genet", "Hickey et al. 2013 Genet Med (ACMG)"]),
    dict(rsid="rs2814778", gene="ACKR1 (DARC)", category="Ancestry marker", trait="Duffy-null blood group",
         effect="C", other="T", tier="B",
         interp={0: "TT — Duffy-positive (typical outside sub-Saharan Africa).", 1: "CT — one Duffy-null allele.", 2: "CC — Duffy-null; protective against P. vivax malaria."},
         note="A classic ancestry-informative marker: the null allele is near-fixed in much of sub-Saharan Africa.",
         refs=["Tournamille et al. 1995 Nat Genet"]),
]

PGX = [
    dict(rsid="rs4244285", gene="CYP2C19", star="*2", effect="A", other="G", tier="B", function="no function",
         refs=["CPIC CYP2C19 guideline (clopidogrel, SSRIs, PPIs)"]),
    dict(rsid="rs4986893", gene="CYP2C19", star="*3", effect="A", other="G", tier="B", function="no function",
         refs=["CPIC CYP2C19 guideline"]),
    dict(rsid="rs12248560", gene="CYP2C19", star="*17", effect="T", other="C", tier="B", function="increased function",
         refs=["CPIC CYP2C19 guideline"]),
    dict(rsid="rs1799853", gene="CYP2C9", star="*2", effect="T", other="C", tier="B", function="decreased function",
         refs=["CPIC warfarin / NSAID / phenytoin guidelines"]),
    dict(rsid="rs1057910", gene="CYP2C9", star="*3", effect="C", other="A", tier="B", function="no function",
         refs=["CPIC warfarin guideline"]),
    dict(rsid="rs9923231", gene="VKORC1", star="-1639G>A", effect="T", other="C", tier="B", function="lower warfarin dose requirement",
         refs=["CPIC warfarin guideline 2017"]),
    dict(rsid="rs4149056", gene="SLCO1B1", star="*5 (521T>C)", effect="C", other="T", tier="B", function="decreased function (statin myopathy risk)",
         refs=["CPIC SLCO1B1 / statin guideline 2022"]),
    dict(rsid="rs3918290", gene="DPYD", star="*2A", effect="T", other="C", tier="B", function="no function (fluoropyrimidine toxicity)",
         refs=["CPIC DPYD guideline"]),
    dict(rsid="rs1142345", gene="TPMT", star="*3C", effect="C", other="T", tier="B", function="no function (thiopurine toxicity)",
         refs=["CPIC thiopurine guideline"]),
    dict(rsid="rs1800460", gene="TPMT", star="*3B component", effect="T", other="C", tier="B", function="no function",
         refs=["CPIC thiopurine guideline"]),
    dict(rsid="rs776746", gene="CYP3A5", star="*3", effect="C", other="T", tier="B", function="no function (non-expresser)",
         refs=["CPIC tacrolimus guideline"]),
    dict(rsid="rs887829", gene="UGT1A1", star="*80 (tags *28)", effect="T", other="C", tier="C", function="decreased function proxy",
         refs=["CPIC atazanavir / irinotecan context; proxy only — *28 itself is a TA-repeat not on arrays"]),
]

PGX_NOT_ASSESSABLE = [
    dict(gene="CYP2D6", reason="Copy-number variants, gene deletions/duplications and hybrid alleles dominate CYP2D6 function and cannot be read from a SNP array. No metabolizer status is reported."),
    dict(gene="HLA-B / HLA-A", reason="HLA alleles (e.g. HLA-B*57:01, *15:02) require HLA typing; array proxies are unreliable across ancestries."),
    dict(gene="UGT1A1 *28", reason="A TA-repeat in the promoter; only a linked proxy (rs887829) is shown."),
]

HEALTH = [
    dict(rsid="rs1800562", gene="HFE", variant="C282Y", condition="Hereditary haemochromatosis (iron overload)", inheritance="Autosomal recessive; low penetrance",
         effect="A", other="G", tier="B", clinvar="Pathogenic",
         interp={0: "No C282Y copy detected at this site.", 1: "One C282Y copy — carrier; disease is rare in carriers.", 2: "Two copies — at-risk genotype; penetrance is incomplete (clinically significant iron overload in a minority, more often men)."}),
    dict(rsid="rs1799945", gene="HFE", variant="H63D", condition="Haemochromatosis modifier", inheritance="Low penetrance; mainly relevant with C282Y",
         effect="G", other="C", tier="C", clinvar="Pathogenic/low penetrance (conflicting)",
         interp={0: "No H63D copy.", 1: "One H63D copy — very common and usually of no consequence on its own.", 2: "Two H63D copies — mild effect on iron indices at most."}),
    dict(rsid="rs6025", gene="F5", variant="Factor V Leiden (R506Q)", condition="Venous thrombosis risk", inheritance="Autosomal dominant risk factor",
         effect="T", other="C", tier="B", clinvar="Pathogenic (risk factor)",
         interp={0: "Factor V Leiden not detected at this site.", 1: "One copy — ~3–8× relative risk of venous clots (absolute risk still low).", 2: "Two copies — higher risk."}),
    dict(rsid="rs1799963", gene="F2", variant="Prothrombin G20210A", condition="Venous thrombosis risk", inheritance="Autosomal dominant risk factor",
         effect="A", other="G", tier="B", clinvar="Pathogenic (risk factor)",
         interp={0: "Not detected at this site.", 1: "One copy — ~2–3× relative risk of venous clots.", 2: "Two copies."}),
    dict(rsid="rs7903146", gene="TCF7L2", variant="intronic", condition="Type 2 diabetes (association)", inheritance="Polygenic",
         effect="T", other="C", tier="C", clinvar="risk factor (GWAS)",
         interp={0: "CC — no copy of the risk allele.", 1: "CT — one copy (odds ratio ~1.4 per copy in large GWAS).", 2: "TT — two copies."}),
    dict(rsid="rs10757274", gene="CDKN2B-AS1 (9p21)", variant="intergenic", condition="Coronary artery disease (association)", inheritance="Polygenic",
         effect="G", other="A", tier="C", clinvar="risk factor (GWAS)",
         interp={0: "AA — no copy.", 1: "AG — one copy (~1.2–1.3× per copy).", 2: "GG — two copies."}),
    dict(rsid="rs10455872", gene="LPA", variant="intronic", condition="Elevated lipoprotein(a) (association)", inheritance="Largely genetic trait",
         effect="G", other="A", tier="B",  clinvar="risk factor",
         interp={0: "AA — no copy of this Lp(a)-raising allele.", 1: "AG — one copy; associated with markedly higher Lp(a).", 2: "GG — two copies."}),
]

APOE = dict(rsids=("rs429358", "rs7412"), tier="B",
            note="APOE ε4 is the strongest common genetic risk factor for late-onset Alzheimer's disease, but it is neither necessary nor sufficient. Many ε4 carriers never develop dementia. This result is hidden by default in the atlas.")

NOT_ASSESSED_HEALTH = [
    "BRCA1/BRCA2: 23andMe v5 tests only 3 founder variants out of thousands of known pathogenic variants. A negative array result means almost nothing for hereditary breast/ovarian cancer risk.",
    "Lynch syndrome, familial hypercholesterolaemia and most cardiomyopathy genes: mostly not covered by the array.",
    "Rare variants in general: consumer arrays have high false-positive rates for very rare variants (Weedon et al. 2021 BMJ). Any rare pathogenic finding needs clinical confirmation.",
]

# mtDNA diagnostic positions along the R > JT > T > T1 path (PhyloTree build 17, rCRS coordinates).
MT_PATH = [
    ("R",  [(12705, "C"), (16223, "C")]),
    ("JT", [(11251, "G"), (15452, "A"), (16126, "C")]),
    ("T",  [(709, "A"), (1888, "A"), (4917, "G"), (8697, "A"), (10463, "C"), (13368, "A"), (14905, "A"), (15607, "G"), (15928, "A"), (16294, "T")]),
    ("T1", [(12633, "A"), (16163, "G"), (16186, "T"), (16189, "C")]),
]
# rCRS is haplogroup H; carrying these non-rCRS alleles shows the lineage is not H.
MT_NON_H = [(2706, "G"), (7028, "T"), (11719, "A"), (73, "G")]

# Plain-language answers per effect-allele count: (answer, confidence).
# Confidence words: "Very likely" (>~85%), "Likely" (~65–85%), "Leaning" (weak shift), "Small effect".
ANSWERS = {
    "rs12913832": {0: ("Brown eyes", "Very likely"), 1: ("Brown or hazel eyes", "Likely"), 2: ("Blue or light eyes", "Very likely")},
    "rs1800407": {0: ("No green/hazel modifier", "Very likely"), 1: ("Carries a green/hazel modifier", "Small effect"), 2: ("Two green/hazel modifiers", "Small effect")},
    "rs1426654": {0: ("Darker-pigmentation version", "Likely"), 1: ("One lighter-skin copy: intermediate", "Leaning"), 2: ("Two lighter-skin copies", "Likely")},
    "rs16891982": {0: ("Darker-pigmentation version", "Likely"), 1: ("One lighter copy", "Leaning"), 2: ("Two lighter copies: lighter skin and hair", "Likely")},
    "rs1042602": {0: ("Typical", "Small effect"), 1: ("Slightly lighter / more freckling", "Small effect"), 2: ("Slightly lighter / more freckling", "Small effect")},
    "rs12203592": {0: ("Tans rather than freckles", "Leaning"), 1: ("More freckles and sun sensitivity", "Likely"), 2: ("Freckles and burns easily", "Likely")},
    "rs1805007": {0: ("Not a red-hair carrier here", "Very likely"), 1: ("Red-hair carrier (not red-haired)", "Likely"), 2: ("Red hair", "Very likely")},
    "rs1805008": {0: ("Not a red-hair carrier here", "Very likely"), 1: ("Red-hair carrier (not red-haired)", "Likely"), 2: ("Red hair", "Very likely")},
    "rs3827760": {0: ("Typical West-Eurasian hair shaft", "Likely"), 1: ("Somewhat thicker, straighter hair", "Leaning"), 2: ("Thick, straight hair", "Likely")},
    "rs17822931": {0: ("Wet (sticky) earwax", "Very likely"), 1: ("Wet (sticky) earwax", "Very likely"), 2: ("Dry, flaky earwax; little underarm odour", "Very likely")},
    "rs4988235": {0: ("Likely lactose intolerant as an adult", "Likely"), 1: ("Digests milk as an adult", "Very likely"), 2: ("Digests milk as an adult", "Very likely")},
    "rs671": {0: ("No alcohol flush from ALDH2", "Very likely"), 1: ("Face flushes after alcohol", "Very likely"), 2: ("Strong flush; alcohol poorly tolerated", "Very likely")},
    "rs1229984": {0: ("Typical alcohol metabolism", "Likely"), 1: ("Fast converter; tends to drink less", "Likely"), 2: ("Fast converter", "Likely")},
    "rs762551": {0: ("Slower caffeine metabolism", "Leaning"), 1: ("Intermediate caffeine metabolism", "Leaning"), 2: ("Fast caffeine metabolism", "Leaning")},
    "rs72921001": {0: ("Cilantro tastes normal", "Small effect"), 1: ("A little more likely to find cilantro soapy", "Small effect"), 2: ("More likely to find cilantro soapy", "Small effect")},
    "rs1815739": {0: ("Sprint/power-type muscle (RR)", "Small effect"), 1: ("Mixed power/endurance (RX)", "Small effect"), 2: ("Endurance-leaning (XX)", "Small effect")},
    "rs4680": {0: ("Faster dopamine clearance (Val/Val)", "Small effect"), 1: ("Intermediate (Val/Met)", "Small effect"), 2: ("Slower dopamine clearance (Met/Met)", "Small effect")},
    "rs1801133": {0: ("Normal folate enzyme", "Very likely"), 1: ("Slightly reduced folate enzyme; not clinically meaningful", "Very likely"), 2: ("Reduced folate enzyme; eat folate", "Likely")},
    "rs2814778": {0: ("Duffy-positive blood group", "Very likely"), 1: ("One Duffy-null copy", "Very likely"), 2: ("Duffy-null blood group", "Very likely")},
}

# Additional clinically relevant PGx alleles checked for array COVERAGE (and, when present, genotype).
# role: 'nf' no function, 'dec' decreased, 'inc' increased, 'tag' haplotype tag.
PGX_EXTRA = [
    dict(gene="CYP2C19", star="*4", rsid="rs28399504", effect="G", other="A", role="nf"),
    dict(gene="CYP2C19", star="*8", rsid="rs41291556", effect="C", other="T", role="nf"),
    dict(gene="CYP2C19", star="*9", rsid="rs17884712", effect="A", other="G", role="dec"),
    dict(gene="CYP2C19", star="*35 / *2-haplotype tag", rsid="rs12769205", effect="G", other="A", role="tag",
         note="rs12769205 G is carried on the *2 haplotype; it defines *35 only when rs4244285 (*2) is absent."),
    dict(gene="CYP2C9", star="*5", rsid="rs28371686", effect="G", other="C", role="dec"),
    dict(gene="CYP2C9", star="*6", rsid="rs9332131", effect="D", other="I", role="nf"),
    dict(gene="CYP2C9", star="*8", rsid="rs7900194", effect="A", other="G", role="dec"),
    dict(gene="CYP2C9", star="*11", rsid="rs28371685", effect="T", other="C", role="dec"),
    dict(gene="DPYD", star="*13 (c.1679T>G)", rsid="rs55886062", effect="C", other="A", role="nf"),
    dict(gene="DPYD", star="c.2846A>T", rsid="rs67376798", effect="A", other="T", role="dec"),
    dict(gene="DPYD", star="HapB3 (c.1236G>A)", rsid="rs56038477", effect="T", other="C", role="dec"),
    dict(gene="TPMT", star="*2", rsid="rs1800462", effect="G", other="C", role="nf"),
    dict(gene="NUDT15", star="*3", rsid="rs116855232", effect="T", other="C", role="nf"),
    dict(gene="CYP3A5", star="*6", rsid="rs10264272", effect="T", other="C", role="nf"),
    dict(gene="CYP3A5", star="*7", rsid="rs41303343", effect="I", other="D", role="nf"),
    dict(gene="UGT1A1", star="*6", rsid="rs4148323", effect="A", other="G", role="dec"),
    dict(gene="SLCO1B1", star="c.388A>G (*1B/*15 component)", rsid="rs2306283", effect="G", other="A", role="tag"),
]

# Biological mechanism chains for traits (literature summaries; qualitative, no invented effect sizes).
# explained: how much of the trait's variation this locus is known to account for, qualitatively.
MECHANISM = {
    "rs12913832": dict(chain=["HERC2 intron enhancer (rs12913832)", "controls OCA2 expression in the iris", "OCA2 governs melanin in iris melanocytes", "brown vs blue iris"], explained="most of the blue/brown difference in West Eurasians; shade within brown is polygenic"),
    "rs1800407": dict(chain=["OCA2 coding change R419Q", "slightly reduced OCA2 activity", "less iris melanin", "green/hazel shading"], explained="a small modifier"),
    "rs1426654": dict(chain=["SLC24A5 A111T", "melanosome ion exchange", "melanin production in skin", "lighter skin"], explained="a meaningful minority of skin-tone variation between populations"),
    "rs16891982": dict(chain=["SLC45A2 L374F", "melanosome pH / transport", "less melanin", "lighter skin and hair"], explained="a minority; skin tone is highly polygenic"),
    "rs1042602": dict(chain=["TYR S192Y", "tyrosinase activity", "melanin synthesis", "freckling / lighter pigment"], explained="a small effect"),
    "rs12203592": dict(chain=["IRF4 enhancer", "IRF4 regulates TYR in melanocytes", "tanning response", "freckles & sun sensitivity"], explained="a moderate effect on freckling in Europeans"),
    "rs1805007": dict(chain=["MC1R R151C", "weaker MC1R signalling", "pheomelanin over eumelanin", "red hair (with 2 variants)"], explained="red hair is near-Mendelian: two MC1R 'R' alleles usually needed"),
    "rs1805008": dict(chain=["MC1R R160W", "weaker MC1R signalling", "pheomelanin over eumelanin", "red hair (with 2 variants)"], explained="as above"),
    "rs3827760": dict(chain=["EDAR V370A", "stronger EDAR signalling in hair follicles", "thicker hair shaft", "thick, straight hair"], explained="a large share of hair-thickness differences in East Asia"),
    "rs17822931": dict(chain=["ABCC11 G180R", "transporter lost in apocrine glands", "no secretion of lipids", "dry earwax, low odour"], explained="essentially the whole trait (recessive)"),
    "rs4988235": dict(chain=["MCM6 intron (LCT enhancer)", "keeps LCT switched on after weaning", "lactase in the adult gut", "digests milk as an adult"], explained="most lactase persistence in Europeans and the steppe; other alleles exist elsewhere"),
    "rs671": dict(chain=["ALDH2 E504K", "inactive aldehyde dehydrogenase", "acetaldehyde builds up", "facial flush"], explained="essentially the whole flush trait"),
    "rs1229984": dict(chain=["ADH1B R48H", "faster ethanol → acetaldehyde", "earlier aversive effects", "tends to drink less"], explained="a moderate effect on drinking"),
    "rs762551": dict(chain=["CYP1A2 promoter (*1F)", "more inducible enzyme", "faster caffeine clearance", "caffeine tolerance"], explained="a modest effect; smoking matters more"),
    "rs72921001": dict(chain=["olfactory receptor cluster (OR6A2)", "detects aldehydes in cilantro", "perceived 'soapy' smell", "cilantro dislike"], explained="a small share of the trait"),
    "rs1815739": dict(chain=["ACTN3 R577X (stop codon)", "α-actinin-3 absent (XX only)", "fast-twitch fibre structure", "sprint vs endurance tendency"], explained="a small effect on performance"),
    "rs4680": dict(chain=["COMT V158M", "less stable enzyme", "slower dopamine breakdown in prefrontal cortex", "subtle cognitive/stress differences"], explained="very small; popular claims overstated"),
    "rs1801133": dict(chain=["MTHFR A222V", "heat-labile enzyme", "less 5-methyl-THF", "higher homocysteine when folate is low"], explained="biochemical effect clear; clinical effect minimal"),
    "rs2814778": dict(chain=["ACKR1 promoter", "no Duffy protein on red cells", "P. vivax cannot enter", "malaria protection"], explained="the whole Duffy-null trait"),
}
